spring:
    application:
        name: config-server 
    cloud:
        config:
            server:
                git:
                    uri: file:///home/ffalcao/git/github/fabianumfalco/workshop-microservices_2025/cloud-lab02/config-repo  
                    default-label: master
    rabbitmq:
        host: localhost
        port: 5672  

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"       